###


GET http://localhost:3000/api/blogs

###

GET http://localhost:3000/api/blogs/65a0eb85795c91d7a9f50598

###

POST http://localhost:3000/api/blogs
Content-Type:application/json

{
    "title": "Test Blog",
    "author": "Test Author",
    "url": "http://test.com",
    "likes": 0
}

### 

DELETE http://localhost:3000/api/blogs/65a0eb85795c91d7a9f50598
